apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: roboshop-dev
    region: us-east-1
managedNodeGroups:
  - name: roboshop-dev
    instanceTypes: ["t3.micro", "c3.small","c4.medium","c5.medium"]
    desiredCapacity: 3 #  by default this value is 3
    spot: true